version: '3.8'

services:
  nginx:
    image: nginx:1.19-alpine
    container_name: leo-NGINX
    restart: always
    ports:
      - 880:80
    volumes:
      - ./code:/code
      - ./nginx/sites/:/etc/nginx/conf.d
    links:
      - php
  php:
    build:
      context: ""
      dockerfile: Dockerfile
    container_name: leo-PHP_FPM
    restart: always
    working_dir: /var/www/
    volumes:
      - ./code:/code
      - ./root:/root
